Update patch set 2
Patch Set 2: Linux-GCC-1

Build Failed http://source.kaidimensional.de:8080/job/psv/job/psv-gcc/566/
../external/repo/portaudio/src/hostapi/alsa/pa_linux_alsa.c:183:1: warning: 'snd_pcm_sw_params_set_xfer_align' is deprecated [-Wdeprecated-declarations]
 _PA_DEFINE_FUNC(snd_pcm_sw_params_set_xfer_align);
 ^~~~~~~~~~~~~~~
In file included from /usr/include/alsa/asoundlib.h:54,
                 from ../external/repo/portaudio/src/hostapi/alsa/pa_linux_alsa.c:52:
/usr/include/alsa/pcm.h:1302:5: note: declared here
 int snd_pcm_sw_params_set_xfer_align(snd_pcm_t *pcm, snd_pcm_sw_params_t *params, snd_pcm_uframes_t val) __attribute__((deprecated));
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../external/repo/portaudio/src/hostapi/alsa/pa_linux_alsa.c: In function 'PaAlsa_LoadLibrary':
../external/repo/portaudio/src/hostapi/alsa/pa_linux_alsa.c:463:5: warning: 'snd_pcm_sw_params_set_xfer_align' is deprecated [-Wdeprecated-declarations]
     _PA_LOAD_FUNC(snd_pcm_sw_params_set_xfer_align);
     ^~~~~~~~~~~~~
In file included from /usr/include/alsa/asoundlib.h:54,
                 from ../external/repo/portaudio/src/hostapi/alsa/pa_linux_alsa.c:52:
/usr/include/alsa/pcm.h:1302:5: note: declared here
 int snd_pcm_sw_params_set_xfer_align(snd_pcm_t *pcm, snd_pcm_sw_params_t *params, snd_pcm_uframes_t val) __attribute__((deprecated));
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../external/repo/portaudio/src/hostapi/alsa/pa_linux_alsa.c: In function 'BuildDeviceList':
../external/repo/portaudio/src/hostapi/alsa/pa_linux_alsa.c:1299:48: warning: '%d' directive output may be truncated writing between 1 and 11 bytes into a region of size between 0 and 49 [-Wformat-truncation=]
             snprintf( buf, sizeof (buf), "%s%s,%d", hwPrefix, alsaCardName, devIdx );
                                                ^~
../external/repo/portaudio/src/hostapi/alsa/pa_linux_alsa.c:1299:13: note: 'snprintf' output 3 or more bytes (assuming 52) into a destination of size 50
             snprintf( buf, sizeof (buf), "%s%s,%d", hwPrefix, alsaCardName, devIdx );
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../external/repo/portaudio/src/hostapi/alsa/pa_linux_alsa.c:183:1: warning: 'snd_pcm_sw_params_set_xfer_align' is deprecated [-Wdeprecated-declarations]
 _PA_DEFINE_FUNC(snd_pcm_sw_params_set_xfer_align);
 ^~~~~~~~~~~~~~~
In file included from /usr/include/alsa/asoundlib.h:54,
                 from ../external/repo/portaudio/src/hostapi/alsa/pa_linux_alsa.c:52:
/usr/include/alsa/pcm.h:1302:5: note: declared here
 int snd_pcm_sw_params_set_xfer_align(snd_pcm_t *pcm, snd_pcm_sw_params_t *params, snd_pcm_uframes_t val) __attribute__((deprecated));
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../external/repo/portaudio/src/hostapi/alsa/pa_linux_alsa.c: In function 'PaAlsa_LoadLibrary':
../external/repo/portaudio/src/hostapi/alsa/pa_linux_alsa.c:463:5: warning: 'snd_pcm_sw_params_set_xfer_align' is deprecated [-Wdeprecated-declarations]
     _PA_LOAD_FUNC(snd_pcm_sw_params_set_xfer_align);
     ^~~~~~~~~~~~~
In file included from /usr/include/alsa/asoundlib.h:54,
                 from ../external/repo/portaudio/src/hostapi/alsa/pa_linux_alsa.c:52:
/usr/include/alsa/pcm.h:1302:5: note: declared here
 int snd_pcm_sw_params_set_xfer_align(snd_pcm_t *pcm, snd_pcm_sw_params_t *params, snd_pcm_uframes_t val) __attribute__((deprecated));
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../external/repo/portaudio/src/hostapi/alsa/pa_linux_alsa.c: In function 'BuildDeviceList':
../external/repo/portaudio/src/hostapi/alsa/pa_linux_alsa.c:1299:48: warning: '%d' directive output may be truncated writing between 1 and 11 bytes into a region of size between 0 and 49 [-Wformat-truncation=]
             snprintf( buf, sizeof (buf), "%s%s,%d", hwPrefix, alsaCardName, devIdx );
                                                ^~
../external/repo/portaudio/src/hostapi/alsa/pa_linux_alsa.c:1299:13: note: 'snprintf' output 3 or more bytes (assuming 52) into a destination of size 50
             snprintf( buf, sizeof (buf), "%s%s,%d", hwPrefix, alsaCardName, devIdx );
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
FAILED: tests/CMakeFiles/tests.dir/sequencer/audio/sample_test.cpp.o 
/usr/bin/g++-8  -DCATCH_CONFIG_ENABLE_ALL_STRINGMAKERS -I../tests -I../external/include -I../include -Iinclude -I../external/repo/portaudio/include -I../external/repo/rtmidi -std=gnu++17 -MD -MT tests/CMakeFiles/tests.dir/sequencer/audio/sample_test.cpp.o -MF tests/CMakeFiles/tests.dir/sequencer/audio/sample_test.cpp.o.d -o tests/CMakeFiles/tests.dir/sequencer/audio/sample_test.cpp.o -c ../tests/sequencer/audio/sample_test.cpp
In file included from ../tests/sequencer/audio/sample_test.cpp:1:
../include/sequencer/audio/sample.hpp: In member function 'constexpr bool sequencer::audio::sample_read_write_base_t::has_frames_left() const':
../include/sequencer/audio/sample.hpp:129:59: error: call to non-'constexpr' function 'sequencer::audio::sample_t::size_type sequencer::audio::sample_t::number_of_frames() const'
             return frame_index_ < sample_.number_of_frames();
                                   ~~~~~~~~~~~~~~~~~~~~~~~~^~
../include/sequencer/audio/sample.hpp: In member function 'constexpr sequencer::audio::sample_read_write_base_t::size_type sequencer::audio::sample_read_write_base_t::frames_to_copy(sequencer::audio::sample_read_write_base_t::size_type) const':
../include/sequencer/audio/sample.hpp:135:62: error: call to non-'constexpr' function 'sequencer::audio::sample_t::size_type sequencer::audio::sample_t::number_of_frames() const'
             const auto frames_left = sample_.number_of_frames() - frame_index_;
                                      ~~~~~~~~~~~~~~~~~~~~~~~~^~
In file included from ../include/sequencer/midi/message/message_type.hpp:3,
                 from ../include/sequencer/midi/message/system_exclusive.hpp:4,
                 from ../tests/sequencer/midi/message/system_exclusive_test.cpp:1:
../include/sequencer/midi/message/system_exclusive.hpp: In instantiation of 'constexpr sequencer::midi::message_t<(8 + (2 * number_of_entries))> sequencer::midi::system::exclusive::realtime::key_based_instrument_control(uint8_t, uint8_t, uint8_t, const std::array<std::pair<unsigned char, unsigned char>, number_of_entries>&) [with long unsigned int number_of_entries = 1; sequencer::midi::message_t<(8 + (2 * number_of_entries))> = std::array<std::byte, 10>; uint8_t = unsigned char]':
../tests/sequencer/midi/message/system_exclusive_test.cpp:148:98:   required from here
/usr/include/c++/8/array:94:12: note: 'sequencer::midi::message_t<6>' {aka 'struct std::array<std::byte, 6>'} has no user-provided default constructor
     struct array
            ^~~~~
/usr/include/c++/8/array:110:56: note: and the implicitly-defined constructor does not initialize 'std::byte std::array<std::byte, 6>::_M_elems [6]'
       typename _AT_Type::_Type                         _M_elems;
                                                        ^~~~~~~~
../include/sequencer/midi/message/system_exclusive.hpp: In instantiation of 'constexpr sequencer::midi::message_t<(8 + (2 * number_of_entries))> sequencer::midi::system::exclusive::realtime::key_based_instrument_control(uint8_t, uint8_t, uint8_t, const std::array<std::pair<unsigned char, unsigned char>, number_of_entries>&) [with long unsigned int number_of_entries = 2; sequencer::midi::message_t<(8 + (2 * number_of_entries))> = std::array<std::byte, 12>; uint8_t = unsigned char]':
../tests/sequencer/midi/message/system_exclusive_test.cpp:176:98:   required from here
/usr/include/c++/8/array:94:12: note: 'sequencer::midi::message_t<8>' {aka 'struct std::array<std::byte, 8>'} has no user-provided default constructor
     struct array
            ^~~~~
/usr/include/c++/8/array:110:56: note: and the implicitly-defined constructor does not initialize 'std::byte std::array<std::byte, 8>::_M_elems [8]'
       typename _AT_Type::_Type                         _M_elems;
                                                        ^~~~~~~~
../include/sequencer/midi/message/system_exclusive.hpp: In instantiation of 'constexpr sequencer::midi::message_t<((9 + ((sizeof (Id) + sizeof (Value)) * number_of_values)) + (2 * number_of_slots))> sequencer::midi::system::exclusive::realtime::global_parameter_control(uint8_t, const std::array<std::pair<_T1, _T2>, number_of_values>&, const std::array<short unsigned int, number_of_slots>&) [with Id = unsigned char; Value = unsigned char; long unsigned int number_of_values = 1; long unsigned int number_of_slots = 0; sequencer::midi::message_t<((9 + ((sizeof (Id) + sizeof (Value)) * number_of_values)) + (2 * number_of_slots))> = std::array<std::byte, 11>; uint8_t = unsigned char]':
../tests/sequencer/midi/message/system_exclusive_test.cpp:358:75:   required from here
/usr/include/c++/8/array:94:12: note: 'sequencer::midi::message_t<7>' {aka 'struct std::array<std::byte, 7>'} has no user-provided default constructor
     struct array
            ^~~~~
/usr/include/c++/8/array:110:56: note: and the implicitly-defined constructor does not initialize 'std::byte std::array<std::byte, 7>::_M_elems [7]'
       typename _AT_Type::_Type                         _M_elems;
                                                        ^~~~~~~~
../include/sequencer/midi/message/system_exclusive.hpp: In instantiation of 'constexpr sequencer::midi::message_t<((9 + ((sizeof (Id) + sizeof (Value)) * number_of_values)) + (2 * number_of_slots))> sequencer::midi::system::exclusive::realtime::global_parameter_control(uint8_t, const std::array<std::pair<_T1, _T2>, number_of_values>&, const std::array<short unsigned int, number_of_slots>&) [with Id = unsigned char; Value = unsigned char; long unsigned int number_of_values = 1; long unsigned int number_of_slots = 1; sequencer::midi::message_t<((9 + ((sizeof (Id) + sizeof (Value)) * number_of_values)) + (2 * number_of_slots))> = std::array<std::byte, 13>; uint8_t = unsigned char]':
../tests/sequencer/midi/message/system_exclusive_test.cpp:384:86:   required from here
/usr/include/c++/8/array:94:12: note: 'sequencer::midi::message_t<9>' {aka 'struct std::array<std::byte, 9>'} has no user-provided default constructor
     struct array
            ^~~~~
/usr/include/c++/8/array:110:56: note: and the implicitly-defined constructor does not initialize 'std::byte std::array<std::byte, 9>::_M_elems [9]'
       typename _AT_Type::_Type                         _M_elems;
                                                        ^~~~~~~~
../include/sequencer/midi/message/system_exclusive.hpp: In instantiation of 'constexpr sequencer::midi::message_t<((9 + ((sizeof (Id) + sizeof (Value)) * number_of_values)) + (2 * number_of_slots))> sequencer::midi::system::exclusive::realtime::global_parameter_control(uint8_t, const std::array<std::pair<_T1, _T2>, number_of_values>&, const std::array<short unsigned int, number_of_slots>&) [with Id = unsigned char; Value = unsigned char; long unsigned int number_of_values = 1; long unsigned int number_of_slots = 2; sequencer::midi::message_t<((9 + ((sizeof (Id) + sizeof (Value)) * number_of_values)) + (2 * number_of_slots))> = std::array<std::byte, 15>; uint8_t = unsigned char]':
../tests/sequencer/midi/message/system_exclusive_test.cpp:412:86:   required from here
/usr/include/c++/8/array:94:12: note: 'sequencer::midi::message_t<11>' {aka 'struct std::array<std::byte, 11>'} has no user-provided default constructor
     struct array
            ^~~~~
/usr/include/c++/8/array:110:56: note: and the implicitly-defined constructor does not initialize 'std::byte std::array<std::byte, 11>::_M_elems [11]'
       typename _AT_Type::_Type                         _M_elems;
                                                        ^~~~~~~~
../include/sequencer/midi/message/system_exclusive.hpp: In instantiation of 'constexpr sequencer::midi::message_t<((9 + ((sizeof (Id) + sizeof (Value)) * number_of_values)) + (2 * number_of_slots))> sequencer::midi::system::exclusive::realtime::global_parameter_control(uint8_t, const std::array<std::pair<_T1, _T2>, number_of_values>&, const std::array<short unsigned int, number_of_slots>&) [with Id = unsigned char; Value = unsigned char; long unsigned int number_of_values = 2; long unsigned int number_of_slots = 0; sequencer::midi::message_t<((9 + ((sizeof (Id) + sizeof (Value)) * number_of_values)) + (2 * number_of_slots))> = std::array<std::byte, 13>; uint8_t = unsigned char]':
../tests/sequencer/midi/message/system_exclusive_test.cpp:442:75:   required from here
/usr/include/c++/8/array:94:12: note: 'sequencer::midi::message_t<9>' {aka 'struct std::array<std::byte, 9>'} has no user-provided default constructor
     struct array
            ^~~~~
/usr/include/c++/8/array:110:56: note: and the implicitly-defined constructor does not initialize 'std::byte std::array<std::byte, 9>::_M_elems [9]'
       typename _AT_Type::_Type                         _M_elems;
                                                        ^~~~~~~~
../include/sequencer/midi/message/system_exclusive.hpp: In instantiation of 'constexpr sequencer::midi::message_t<((9 + ((sizeof (Id) + sizeof (Value)) * number_of_values)) + (2 * number_of_slots))> sequencer::midi::system::exclusive::realtime::global_parameter_control(uint8_t, const std::array<std::pair<_T1, _T2>, number_of_values>&, const std::array<short unsigned int, number_of_slots>&) [with Id = unsigned char; Value = short unsigned int; long unsigned int number_of_values = 2; long unsigned int number_of_slots = 0; sequencer::midi::message_t<((9 + ((sizeof (Id) + sizeof (Value)) * number_of_values)) + (2 * number_of_slots))> = std::array<std::byte, 15>; uint8_t = unsigned char]':
../tests/sequencer/midi/message/system_exclusive_test.cpp:470:75:   required from here
/usr/include/c++/8/array:94:12: note: 'sequencer::midi::message_t<11>' {aka 'struct std::array<std::byte, 11>'} has no user-provided default constructor
     struct array
            ^~~~~
/usr/include/c++/8/array:110:56: note: and the implicitly-defined constructor does not initialize 'std::byte std::array<std::byte, 11>::_M_elems [11]'
       typename _AT_Type::_Type                         _M_elems;
                                                        ^~~~~~~~
../include/sequencer/midi/message/system_exclusive.hpp: In instantiation of 'constexpr sequencer::midi::message_t<((9 + ((sizeof (Id) + sizeof (Value)) * number_of_values)) + (2 * number_of_slots))> sequencer::midi::system::exclusive::realtime::global_parameter_control(uint8_t, const std::array<std::pair<_T1, _T2>, number_of_values>&, const std::array<short unsigned int, number_of_slots>&) [with Id = short unsigned int; Value = unsigned char; long unsigned int number_of_values = 2; long unsigned int number_of_slots = 0; sequencer::midi::message_t<((9 + ((sizeof (Id) + sizeof (Value)) * number_of_values)) + (2 * number_of_slots))> = std::array<std::byte, 15>; uint8_t = unsigned char]':
../tests/sequencer/midi/message/system_exclusive_test.cpp:500:75:   required from here
/usr/include/c++/8/array:94:12: note: 'sequencer::midi::message_t<11>' {aka 'struct std::array<std::byte, 11>'} has no user-provided default constructor
     struct array
            ^~~~~
/usr/include/c++/8/array:110:56: note: and the implicitly-defined constructor does not initialize 'std::byte std::array<std::byte, 11>::_M_elems [11]'
       typename _AT_Type::_Type                         _M_elems;
                                                        ^~~~~~~~
../include/sequencer/midi/message/system_exclusive.hpp: In instantiation of 'constexpr sequencer::midi::message_t<((9 + ((sizeof (Id) + sizeof (Value)) * number_of_values)) + (2 * number_of_slots))> sequencer::midi::system::exclusive::realtime::global_parameter_control(uint8_t, const std::array<std::pair<_T1, _T2>, number_of_values>&, const std::array<short unsigned int, number_of_slots>&) [with Id = short unsigned int; Value = short unsigned int; long unsigned int number_of_values = 2; long unsigned int number_of_slots = 0; sequencer::midi::message_t<((9 + ((sizeof (Id) + sizeof (Value)) * number_of_values)) + (2 * number_of_slots))> = std::array<std::byte, 17>; uint8_t = unsigned char]':
../tests/sequencer/midi/message/system_exclusive_test.cpp:530:75:   required from here
/usr/include/c++/8/array:94:12: note: 'sequencer::midi::message_t<13>' {aka 'struct std::array<std::byte, 13>'} has no user-provided default constructor
     struct array
            ^~~~~
/usr/include/c++/8/array:110:56: note: and the implicitly-defined constructor does not initialize 'std::byte std::array<std::byte, 13>::_M_elems [13]'
       typename _AT_Type::_Type                         _M_elems;
                                                        ^~~~~~~~

Patch-set: 2
Reviewer: Gerrit User 1016797 <1016797@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Linux-GCC=-1