Update patch set 11
Patch Set 11: Linux-GCC-1

Build Failed http://source.kaidimensional.de:8080/job/psv/job/psv-gcc/516/
FAILED: tests/CMakeFiles/tests.dir/sequencer/midi/track_test.cpp.o 
/usr/bin/g++-8  -DCATCH_CONFIG_ENABLE_ALL_STRINGMAKERS -I../tests -I../external/include -I../external/repo/install/rtmidi/include -I../include -std=gnu++17 -MD -MT tests/CMakeFiles/tests.dir/sequencer/midi/track_test.cpp.o -MF tests/CMakeFiles/tests.dir/sequencer/midi/track_test.cpp.o.d -o tests/CMakeFiles/tests.dir/sequencer/midi/track_test.cpp.o -c ../tests/sequencer/midi/track_test.cpp
In file included from ../tests/sequencer/midi/track_test.cpp:1:
../include/sequencer/chrono/sequencer_clock.hpp: In instantiation of 'class sequencer::chrono::sequencer_clock<const sequencer::chrono::testing_clock<long int, std::ratio<1, 1000000000>, true>&>':
../tests/sequencer/midi/track_test.cpp:514:30:   required from here
../include/sequencer/chrono/sequencer_clock.hpp:21:24: error: static assertion failed: Underlying clock must be steady
         static_assert( underlying_clock_type::is_steady, "Underlying clock must be steady" );
                        ^~~~~~~~~~~~~~~~~~~~~
FAILED: tests/CMakeFiles/tests.dir/sequencer/midi/clock_test.cpp.o 
/usr/bin/g++-8  -DCATCH_CONFIG_ENABLE_ALL_STRINGMAKERS -I../tests -I../external/include -I../external/repo/install/rtmidi/include -I../include -std=gnu++17 -MD -MT tests/CMakeFiles/tests.dir/sequencer/midi/clock_test.cpp.o -MF tests/CMakeFiles/tests.dir/sequencer/midi/clock_test.cpp.o.d -o tests/CMakeFiles/tests.dir/sequencer/midi/clock_test.cpp.o -c ../tests/sequencer/midi/clock_test.cpp
In file included from ../tests/sequencer/midi/clock_test.cpp:2:
../include/sequencer/chrono/sequencer_clock.hpp: In instantiation of 'class sequencer::chrono::sequencer_clock<const sequencer::chrono::testing_clock<long int, std::ratio<1, 1000000000>, true>&>':
../tests/sequencer/midi/clock_test.cpp:105:30:   required from here
../include/sequencer/chrono/sequencer_clock.hpp:21:24: error: static assertion failed: Underlying clock must be steady
         static_assert( underlying_clock_type::is_steady, "Underlying clock must be steady" );
                        ^~~~~~~~~~~~~~~~~~~~~
FAILED: tests/CMakeFiles/tests.dir/sequencer/chrono/sequencer_clock_test.cpp.o 
/usr/bin/g++-8  -DCATCH_CONFIG_ENABLE_ALL_STRINGMAKERS -I../tests -I../external/include -I../external/repo/install/rtmidi/include -I../include -std=gnu++17 -MD -MT tests/CMakeFiles/tests.dir/sequencer/chrono/sequencer_clock_test.cpp.o -MF tests/CMakeFiles/tests.dir/sequencer/chrono/sequencer_clock_test.cpp.o.d -o tests/CMakeFiles/tests.dir/sequencer/chrono/sequencer_clock_test.cpp.o -c ../tests/sequencer/chrono/sequencer_clock_test.cpp
In file included from ../tests/sequencer/chrono/sequencer_clock_test.cpp:3:
../include/sequencer/chrono/sequencer_clock.hpp: In instantiation of 'class sequencer::chrono::sequencer_clock<const sequencer::chrono::testing_clock<long int, std::ratio<1, 1000000000>, true>&>':
../tests/sequencer/chrono/sequencer_clock_test.cpp:20:68:   required from here
../include/sequencer/chrono/sequencer_clock.hpp:21:24: error: static assertion failed: Underlying clock must be steady
         static_assert( underlying_clock_type::is_steady, "Underlying clock must be steady" );
                        ^~~~~~~~~~~~~~~~~~~~~
In file included from ../include/sequencer/midi/message/message_type.hpp:3,
                 from ../include/sequencer/midi/message/system_exclusive.hpp:3,
                 from ../tests/sequencer/midi/message/system_exclusive_test.cpp:1:
../include/sequencer/midi/message/system_exclusive.hpp: In instantiation of 'constexpr sequencer::midi::message_t<(8 + (2 * number_of_entries))> sequencer::midi::system::exclusive::realtime::key_based_instrument_control(uint8_t, uint8_t, uint8_t, const std::array<std::pair<unsigned char, unsigned char>, number_of_entries>&) [with long unsigned int number_of_entries = 1; sequencer::midi::message_t<(8 + (2 * number_of_entries))> = std::array<std::byte, 10>; uint8_t = unsigned char]':
../tests/sequencer/midi/message/system_exclusive_test.cpp:148:98:   required from here
/usr/include/c++/8/array:94:12: note: 'sequencer::midi::message_t<6>' {aka 'struct std::array<std::byte, 6>'} has no user-provided default constructor
     struct array
            ^~~~~
/usr/include/c++/8/array:110:56: note: and the implicitly-defined constructor does not initialize 'std::byte std::array<std::byte, 6>::_M_elems [6]'
       typename _AT_Type::_Type                         _M_elems;
                                                        ^~~~~~~~
../include/sequencer/midi/message/system_exclusive.hpp: In instantiation of 'constexpr sequencer::midi::message_t<(8 + (2 * number_of_entries))> sequencer::midi::system::exclusive::realtime::key_based_instrument_control(uint8_t, uint8_t, uint8_t, const std::array<std::pair<unsigned char, unsigned char>, number_of_entries>&) [with long unsigned int number_of_entries = 2; sequencer::midi::message_t<(8 + (2 * number_of_entries))> = std::array<std::byte, 12>; uint8_t = unsigned char]':
../tests/sequencer/midi/message/system_exclusive_test.cpp:176:98:   required from here
/usr/include/c++/8/array:94:12: note: 'sequencer::midi::message_t<8>' {aka 'struct std::array<std::byte, 8>'} has no user-provided default constructor
     struct array
            ^~~~~
/usr/include/c++/8/array:110:56: note: and the implicitly-defined constructor does not initialize 'std::byte std::array<std::byte, 8>::_M_elems [8]'
       typename _AT_Type::_Type                         _M_elems;
                                                        ^~~~~~~~
../include/sequencer/midi/message/system_exclusive.hpp: In instantiation of 'constexpr sequencer::midi::message_t<((9 + ((sizeof (Id) + sizeof (Value)) * number_of_values)) + (2 * number_of_slots))> sequencer::midi::system::exclusive::realtime::global_parameter_control(uint8_t, const std::array<std::pair<_T1, _T2>, number_of_values>&, const std::array<short unsigned int, number_of_slots>&) [with Id = unsigned char; Value = unsigned char; long unsigned int number_of_values = 1; long unsigned int number_of_slots = 0; sequencer::midi::message_t<((9 + ((sizeof (Id) + sizeof (Value)) * number_of_values)) + (2 * number_of_slots))> = std::array<std::byte, 11>; uint8_t = unsigned char]':
../tests/sequencer/midi/message/system_exclusive_test.cpp:358:75:   required from here
/usr/include/c++/8/array:94:12: note: 'sequencer::midi::message_t<7>' {aka 'struct std::array<std::byte, 7>'} has no user-provided default constructor
     struct array
            ^~~~~
/usr/include/c++/8/array:110:56: note: and the implicitly-defined constructor does not initialize 'std::byte std::array<std::byte, 7>::_M_elems [7]'
       typename _AT_Type::_Type                         _M_elems;
                                                        ^~~~~~~~
../include/sequencer/midi/message/system_exclusive.hpp: In instantiation of 'constexpr sequencer::midi::message_t<((9 + ((sizeof (Id) + sizeof (Value)) * number_of_values)) + (2 * number_of_slots))> sequencer::midi::system::exclusive::realtime::global_parameter_control(uint8_t, const std::array<std::pair<_T1, _T2>, number_of_values>&, const std::array<short unsigned int, number_of_slots>&) [with Id = unsigned char; Value = unsigned char; long unsigned int number_of_values = 1; long unsigned int number_of_slots = 1; sequencer::midi::message_t<((9 + ((sizeof (Id) + sizeof (Value)) * number_of_values)) + (2 * number_of_slots))> = std::array<std::byte, 13>; uint8_t = unsigned char]':
../tests/sequencer/midi/message/system_exclusive_test.cpp:384:86:   required from here
/usr/include/c++/8/array:94:12: note: 'sequencer::midi::message_t<9>' {aka 'struct std::array<std::byte, 9>'} has no user-provided default constructor
     struct array
            ^~~~~
/usr/include/c++/8/array:110:56: note: and the implicitly-defined constructor does not initialize 'std::byte std::array<std::byte, 9>::_M_elems [9]'
       typename _AT_Type::_Type                         _M_elems;
                                                        ^~~~~~~~
../include/sequencer/midi/message/system_exclusive.hpp: In instantiation of 'constexpr sequencer::midi::message_t<((9 + ((sizeof (Id) + sizeof (Value)) * number_of_values)) + (2 * number_of_slots))> sequencer::midi::system::exclusive::realtime::global_parameter_control(uint8_t, const std::array<std::pair<_T1, _T2>, number_of_values>&, const std::array<short unsigned int, number_of_slots>&) [with Id = unsigned char; Value = unsigned char; long unsigned int number_of_values = 1; long unsigned int number_of_slots = 2; sequencer::midi::message_t<((9 + ((sizeof (Id) + sizeof (Value)) * number_of_values)) + (2 * number_of_slots))> = std::array<std::byte, 15>; uint8_t = unsigned char]':
../tests/sequencer/midi/message/system_exclusive_test.cpp:412:86:   required from here
/usr/include/c++/8/array:94:12: note: 'sequencer::midi::message_t<11>' {aka 'struct std::array<std::byte, 11>'} has no user-provided default constructor
     struct array
            ^~~~~
/usr/include/c++/8/array:110:56: note: and the implicitly-defined constructor does not initialize 'std::byte std::array<std::byte, 11>::_M_elems [11]'
       typename _AT_Type::_Type                         _M_elems;
                                                        ^~~~~~~~
../include/sequencer/midi/message/system_exclusive.hpp: In instantiation of 'constexpr sequencer::midi::message_t<((9 + ((sizeof (Id) + sizeof (Value)) * number_of_values)) + (2 * number_of_slots))> sequencer::midi::system::exclusive::realtime::global_parameter_control(uint8_t, const std::array<std::pair<_T1, _T2>, number_of_values>&, const std::array<short unsigned int, number_of_slots>&) [with Id = unsigned char; Value = unsigned char; long unsigned int number_of_values = 2; long unsigned int number_of_slots = 0; sequencer::midi::message_t<((9 + ((sizeof (Id) + sizeof (Value)) * number_of_values)) + (2 * number_of_slots))> = std::array<std::byte, 13>; uint8_t = unsigned char]':
../tests/sequencer/midi/message/system_exclusive_test.cpp:442:75:   required from here
/usr/include/c++/8/array:94:12: note: 'sequencer::midi::message_t<9>' {aka 'struct std::array<std::byte, 9>'} has no user-provided default constructor
     struct array
            ^~~~~
/usr/include/c++/8/array:110:56: note: and the implicitly-defined constructor does not initialize 'std::byte std::array<std::byte, 9>::_M_elems [9]'
       typename _AT_Type::_Type                         _M_elems;
                                                        ^~~~~~~~
../include/sequencer/midi/message/system_exclusive.hpp: In instantiation of 'constexpr sequencer::midi::message_t<((9 + ((sizeof (Id) + sizeof (Value)) * number_of_values)) + (2 * number_of_slots))> sequencer::midi::system::exclusive::realtime::global_parameter_control(uint8_t, const std::array<std::pair<_T1, _T2>, number_of_values>&, const std::array<short unsigned int, number_of_slots>&) [with Id = unsigned char; Value = short unsigned int; long unsigned int number_of_values = 2; long unsigned int number_of_slots = 0; sequencer::midi::message_t<((9 + ((sizeof (Id) + sizeof (Value)) * number_of_values)) + (2 * number_of_slots))> = std::array<std::byte, 15>; uint8_t = unsigned char]':
../tests/sequencer/midi/message/system_exclusive_test.cpp:470:75:   required from here
/usr/include/c++/8/array:94:12: note: 'sequencer::midi::message_t<11>' {aka 'struct std::array<std::byte, 11>'} has no user-provided default constructor
     struct array
            ^~~~~
/usr/include/c++/8/array:110:56: note: and the implicitly-defined constructor does not initialize 'std::byte std::array<std::byte, 11>::_M_elems [11]'
       typename _AT_Type::_Type                         _M_elems;
                                                        ^~~~~~~~
../include/sequencer/midi/message/system_exclusive.hpp: In instantiation of 'constexpr sequencer::midi::message_t<((9 + ((sizeof (Id) + sizeof (Value)) * number_of_values)) + (2 * number_of_slots))> sequencer::midi::system::exclusive::realtime::global_parameter_control(uint8_t, const std::array<std::pair<_T1, _T2>, number_of_values>&, const std::array<short unsigned int, number_of_slots>&) [with Id = short unsigned int; Value = unsigned char; long unsigned int number_of_values = 2; long unsigned int number_of_slots = 0; sequencer::midi::message_t<((9 + ((sizeof (Id) + sizeof (Value)) * number_of_values)) + (2 * number_of_slots))> = std::array<std::byte, 15>; uint8_t = unsigned char]':
../tests/sequencer/midi/message/system_exclusive_test.cpp:500:75:   required from here
/usr/include/c++/8/array:94:12: note: 'sequencer::midi::message_t<11>' {aka 'struct std::array<std::byte, 11>'} has no user-provided default constructor
     struct array
            ^~~~~
/usr/include/c++/8/array:110:56: note: and the implicitly-defined constructor does not initialize 'std::byte std::array<std::byte, 11>::_M_elems [11]'
       typename _AT_Type::_Type                         _M_elems;
                                                        ^~~~~~~~
../include/sequencer/midi/message/system_exclusive.hpp: In instantiation of 'constexpr sequencer::midi::message_t<((9 + ((sizeof (Id) + sizeof (Value)) * number_of_values)) + (2 * number_of_slots))> sequencer::midi::system::exclusive::realtime::global_parameter_control(uint8_t, const std::array<std::pair<_T1, _T2>, number_of_values>&, const std::array<short unsigned int, number_of_slots>&) [with Id = short unsigned int; Value = short unsigned int; long unsigned int number_of_values = 2; long unsigned int number_of_slots = 0; sequencer::midi::message_t<((9 + ((sizeof (Id) + sizeof (Value)) * number_of_values)) + (2 * number_of_slots))> = std::array<std::byte, 17>; uint8_t = unsigned char]':
../tests/sequencer/midi/message/system_exclusive_test.cpp:530:75:   required from here
/usr/include/c++/8/array:94:12: note: 'sequencer::midi::message_t<13>' {aka 'struct std::array<std::byte, 13>'} has no user-provided default constructor
     struct array
            ^~~~~
/usr/include/c++/8/array:110:56: note: and the implicitly-defined constructor does not initialize 'std::byte std::array<std::byte, 13>::_M_elems [13]'
       typename _AT_Type::_Type                         _M_elems;
                                                        ^~~~~~~~

Patch-set: 11
Reviewer: Gerrit User 1016797 <1016797@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Linux-GCC=-1