Update patch set 16
Patch Set 16: Linux-GCC-1

Build Failed http://source.kaidimensional.de:8080/job/psv/job/psv-gcc/274/
FAILED: tests/CMakeFiles/tests.dir/sequencer/midi/clock_test.cpp.o 
/usr/bin/g++-8  -DCATCH_CONFIG_ENABLE_ALL_STRINGMAKERS -I../external/include -I../external/repo/install/rtmidi/include -I../include -std=gnu++17 -MD -MT tests/CMakeFiles/tests.dir/sequencer/midi/clock_test.cpp.o -MF tests/CMakeFiles/tests.dir/sequencer/midi/clock_test.cpp.o.d -o tests/CMakeFiles/tests.dir/sequencer/midi/clock_test.cpp.o -c ../tests/sequencer/midi/clock_test.cpp
In file included from ../tests/sequencer/midi/clock_test.cpp:1:
../include/sequencer/midi/clock.hpp: In instantiation of 'constexpr sequencer::beat_duration sequencer::midi::clock<Sender>::now_as_beat_duration() const [with Sender = ____C_A_T_C_H____T_E_S_T____0()::<lambda(sequencer::midi::message_type)>]':
../include/sequencer/midi/clock.hpp:72:28:   required from 'void sequencer::midi::clock<Sender>::run() [with Sender = ____C_A_T_C_H____T_E_S_T____0()::<lambda(sequencer::midi::message_type)>]'
../tests/sequencer/midi/clock_test.cpp:28:23:   required from here
../include/sequencer/midi/clock.hpp:96:20: error: no matching function for call to 'sequencer::beat_duration::beat_duration(std::__success_type<std::chrono::duration<long int, std::ratio<1, 1000000000> > >::type, const sequencer::beats_per_minute&)'
             return beat_duration( sequencer_clock_.now() - sequencer_clock::time_point{}, tempo_ );
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ../include/sequencer/midi/clock.hpp:3,
                 from ../tests/sequencer/midi/clock_test.cpp:1:
../include/sequencer/beat_duration.hpp:22:28: note: candidate: 'constexpr sequencer::beat_duration::beat_duration(sequencer::beat_duration::rep)'
         constexpr explicit beat_duration( rep beats ) noexcept : duration_( beats )
                            ^~~~~~~~~~~~~
../include/sequencer/beat_duration.hpp:22:28: note:   candidate expects 1 argument, 2 provided
../include/sequencer/beat_duration.hpp:14:11: note: candidate: 'constexpr sequencer::beat_duration::beat_duration(const sequencer::beat_duration&)'
     class beat_duration
           ^~~~~~~~~~~~~
../include/sequencer/beat_duration.hpp:14:11: note:   candidate expects 1 argument, 2 provided
../include/sequencer/beat_duration.hpp:14:11: note: candidate: 'constexpr sequencer::beat_duration::beat_duration(sequencer::beat_duration&&)'
../include/sequencer/beat_duration.hpp:14:11: note:   candidate expects 1 argument, 2 provided
In file included from ../tests/sequencer/midi/clock_test.cpp:1:
../include/sequencer/midi/clock.hpp: In instantiation of 'constexpr sequencer::beat_duration sequencer::midi::clock<Sender>::now_as_beat_duration() const [with Sender = std::function<void(sequencer::midi::message_type)>]':
../include/sequencer/midi/clock.hpp:72:28:   required from 'void sequencer::midi::clock<Sender>::run() [with Sender = std::function<void(sequencer::midi::message_type)>]'
../tests/sequencer/midi/clock_test.cpp:113:44:   required from here
../include/sequencer/midi/clock.hpp:96:20: error: no matching function for call to 'sequencer::beat_duration::beat_duration(std::__success_type<std::chrono::duration<long int, std::ratio<1, 1000000000> > >::type, const sequencer::beats_per_minute&)'
             return beat_duration( sequencer_clock_.now() - sequencer_clock::time_point{}, tempo_ );
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ../include/sequencer/midi/clock.hpp:3,
                 from ../tests/sequencer/midi/clock_test.cpp:1:
../include/sequencer/beat_duration.hpp:22:28: note: candidate: 'constexpr sequencer::beat_duration::beat_duration(sequencer::beat_duration::rep)'
         constexpr explicit beat_duration( rep beats ) noexcept : duration_( beats )
                            ^~~~~~~~~~~~~
../include/sequencer/beat_duration.hpp:22:28: note:   candidate expects 1 argument, 2 provided
../include/sequencer/beat_duration.hpp:14:11: note: candidate: 'constexpr sequencer::beat_duration::beat_duration(const sequencer::beat_duration&)'
     class beat_duration
           ^~~~~~~~~~~~~
../include/sequencer/beat_duration.hpp:14:11: note:   candidate expects 1 argument, 2 provided
../include/sequencer/beat_duration.hpp:14:11: note: candidate: 'constexpr sequencer::beat_duration::beat_duration(sequencer::beat_duration&&)'
../include/sequencer/beat_duration.hpp:14:11: note:   candidate expects 1 argument, 2 provided
In file included from ../tests/sequencer/midi/clock_test.cpp:1:
../include/sequencer/midi/clock.hpp:87:14: warning: 'void sequencer::midi::clock<Sender>::unlocked_shut_down() noexcept [with Sender = ____C_A_T_C_H____T_E_S_T____0()::<lambda(sequencer::midi::message_type)>]' used but never defined
         void unlocked_shut_down() noexcept
              ^~~~~~~~~~~~~~~~~~

Patch-set: 16
Reviewer: Gerrit User 1016797 <1016797@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: Linux-GCC=-1